### PR TITLE
Part II Feature/specialized exception

### PR DESCRIPTION
**Pull request by Rolf-Smit**
Part II in a series of pull-requests.

**Changes in this pull-request:**

- Added specialized exception `CertificateNotPinnedException` which is a sub-type of `CertificateException` this change allows users of the library to distinguish between not pinned exceptions and other certificate related exceptions.

**Files affected**
- `CertificateNotPinnedException.java` +
- `PinningTrustManager.java`
- `PinningTrustManagerTest.java`

**Release notes:** unless you want to write them yourself I will be doing a separate pull-request for the release notes.

Feel free to pull my fork and test this branch.

### CODE REVIEW

**Comment by Flowdalic** [comment]
It seems you experimented a little bit with git. I either prefer a single commit or, even better, single commits per logical change.

**Comment by Rolf-Smit** [comment]
Haha, I've made a mess haven't I ;) I'm not really experimenting, besides incremental changes (I like to commit my work so I don't lose it) I tried to separate the functional changes in different pull-requests but they turned out to be somewhat depended on each other. Which means I now have to keep those branches up-to-date.

I could have went with separate branches instead which do not depend on each other, but this means that some changes can only be made afterwards.

But the whole point of a pull-request is to merge work into a single reviewable change, I do however try to keep changes within a single commit but sometimes you end-up with incremental changes anyway.

**Comment by Rolf-Smit** [comment]
@Flowdalic I went ahead and squashed the commits into a single one for each of the features.

**Comment by Rolf-Smit** [comment]
@Flowdalic this one is ready.

**Comment by Rolf-Smit** [comment]
Closed because we decided to merge part II, III and IV at once.

**Pull request closed without merging**
